// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

// Prevenir crash fatal se as variáveis não estiverem configuradas
const isSupabaseConfigured = SUPABASE_URL.startsWith('https://') && SUPABASE_PUBLISHABLE_KEY.length > 0;

if (!isSupabaseConfigured) {
  console.error("❌ ERRO CRÍTICO: Variáveis do Supabase ausentes ou inválidas no Vercel.");
}

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : {
    auth: { onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }), getSession: async () => ({ data: { session: null } }) },
    from: () => ({ select: () => ({ order: () => ({ eq: () => Promise.resolve({ data: [], error: null }) }) }) })
  } as any;
